version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: shubham@2805
      MYSQL_DATABASE: employee_db

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  employee-app:
    build: .
    container_name: employee-app

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: shubham@2805

volumes:
  mysql-data: